services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - ./server:/app/server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app/server
    depends_on:
      - redis
      - mongo

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A server.app.celery worker --loglevel=info
    volumes:
      - ./server:/app/server
    environment:
      - PYTHONPATH=/app/server
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
